[platformio]
src_dir = src
include_dir = include

[env:esp32dev]
platform = espressif32@5.4.0
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.partitions = huge_app.csv
build_flags =
    -DCORE_DEBUG_LEVEL=2
    -DCONFIG_ARDUHAL_LOG_COLORS=1
    -DCONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST=0
    -DCONFIG_MBEDTLS_SHA256_ALT=1
    -DARDUINO_ESP32_GIT_VER=0x46d5afb1
    -DCOMPAT_PREVIOUS_ESP_IDF
    -O2
lib_deps =
    bblanchon/ArduinoJson@^7.0.0
    olikraus/U8g2@^2.35.0
    nrf24/RF24@^1.6.1
    LSatan/SmartRC-CC1101-Driver-Lib@^2.5.0
    knolleary/PubSubClient@^2.8
